parallel-jobs = 1

[Instagram]
enabled = false
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk"
github-dlurl = "myst-25/ampy/com.instagram.android"
patcher-args = "--continue-on-error"

[Twitter]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk"
json-key = "X"
dl-keyword = "x"
github-dlurl = "myst-25/ampy/com.twitter.android"
arch = "both"
patcher-args = "--continue-on-error"
