parallel-jobs = 1

[Instagram]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk"
github-dlurl = "myst-25/ampy/com.instagram.android"
version = "433.0.0.4.68"
patcher-args = "--continue-on-error"
arch = "all"

[Twitter]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk"
json-key = "X"
dl-keyword = "x"
github-dlurl = "myst-25/ampy/com.twitter.android"
arch = "all"
patcher-args = "--continue-on-error"
