name: Build YouTube and Music
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Get next version code
        id: next_ver_code
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
          if [ -z "$TAG" ]; then TAG=0; fi
          echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT

      - name: Build APKs
        run: ./build.sh youtube.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}

      - name: Get output
        id: get_output
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
      
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          BODY: ${{ steps.get_output.outputs.BUILD_LOG }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release edit "$TAG" --title "Release" --notes "$BODY"
            gh release upload "$TAG" ./build/* --clobber
          else
            gh release create "$TAG" ./build/* --title "Release" --notes "$BODY"
          fi

      - name: Report to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        if: env.TG_TOKEN != null
        run: |
          cd build || { echo "build folder not found"; exit 1; }

          TG_CHAT="@morphedapps"
          
          YT_VER=$(grep "YouTube-Morphe" ../build.md | head -n1 | awk '{print $NF}')
          YTM_VER=$(grep "Music-Morphe" ../build.md | head -n1 | awk '{print $NF}')
          
          PATCH_TAG=$(curl -sL https://api.github.com/repos/MorpheApp/morphe-patches/releases/latest | jq -r .tag_name)
          PATCH_VER=${PATCH_TAG#v}
          
          DL_BASE="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}"

          MSG="> **Youtube and Yt Music**

          \`youtube: ${YT_VER}\`
          \`yt music: ${YTM_VER}\`

          Install Microg (https://github.com/MorpheApp/MicroG-RE/releases/tag/6.1.4) for non-root YouTube and YT Music APKs  
          Use zygisk-detach (https://github.com/j-hc/zygisk-detach) to detach YouTube and YT Music modules from Play Store  

          Morphe changelog (https://github.com/MorpheApp/morphe-patches/releases/tag/${PATCH_TAG})
          Morphe patched - ${PATCH_VER}

          apk link
          youtube - arm 64 V8a - [Download](${DL_BASE}/youtube-morphe-v${YT_VER}-arm64-v8a.apk)
          youtube - arm 7 - [Download](${DL_BASE}/youtube-morphe-v${YT_VER}-arm-v7a.apk)
          yt music - arm 64 V8a - [Download](${DL_BASE}/music-morphe-v${YTM_VER}-arm64-v8a.apk)
          yt music - arm 7 - [Download](${DL_BASE}/music-morphe-v${YTM_VER}-arm-v7a.apk)

          [Myst25 chat for any discussion](https://t.me/+OQA0X-ECCHI4ZmU1)"

          MSG="$(echo "$MSG" | sed 's/^ \{10\}//')"
          echo "$MSG"
          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
